name: Release on merge

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  release:
    if: "github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: yarn   # change to npm if you use npm

      - name: Read version from package.json
        id: v
        run: node -e "console.log('value=' + require('./package.json').version)" >> "$GITHUB_OUTPUT"

      - name: "Guard: tag & npm version must be new"
        env:
          VERSION: ${{ steps.v.outputs.value }}
        run: |
          TAG="v$VERSION"
          echo "Checking $TAG..."
          git fetch --tags --quiet
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists"; exit 1
          fi
          if npm view elastickbird@"$VERSION" version >/dev/null 2>&1; then
            echo "Version $VERSION already on npm"; exit 1
          fi


      - name: Install deps
        run: yarn install --frozen-lockfile   # or: npm ci

      - name: Build
        run: yarn build                       # or your build cmd; remove if not needed

      - name: Publish to npm
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create git tag
        run: |
          TAG="v${{ steps.v.outputs.value }}"
          git tag -a "$TAG" -m "Elastickbird $TAG"
          git push origin "$TAG"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.v.outputs.value }}
          name: Elastickbird v${{ steps.v.outputs.value }}
          generate_release_notes: true
